---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tapp-controller
  namespace: kube-system

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tapp-controller-role-binding
subjects:
  - kind: ServiceAccount
    name: tapp-controller
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: tapp-controller
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: tapp-controller
  replicas: 1
  template:
    metadata:
      labels:
        app: tapp-controller
    spec:
      serviceAccountName: tapp-controller
      containers:
        - name: tapp-controller
          image: ruijzhan/tapp-controller:v1.1.1
          args:
            - "--register-admission=false"
          imagePullPolicy: "Always"
          resources:
            requests:
              "cpu": "1"
              "memory": "512Mi"
