apiVersion: apps.tkestack.io/v1
kind: TApp
metadata:
  name: example-tapp
  labels:
    app: example-tapp
spec:
  defaultTemplateName: default
  replicas: 3
  selector:
    matchLabels:
      app: example-tapp
  template:
    metadata:
      labels:
        app: example-tapp
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
